<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CitasMedicasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $citas = [
            [
                'numero_cita' => 'CITA-2025-0001',
                'cliente_id' => 1,
                'mascota_id' => 1,
                'empleado_id' => 1, // Dr. Ana María
                'servicio_medico_id' => 1, // Consulta General
                'fecha_hora' => Carbon::now()->addDays(1)->setTime(9, 0),
                'duracion_minutos' => 30,
                'estado' => 'Confirmada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Chequeo de rutina y vacunación',
                'sintomas_observados' => null,
                'precio_estimado' => 85.00,
                'precio_final' => null,
                'observaciones' => 'Cliente puntual, mascota dócil',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0002',
                'cliente_id' => 2,
                'mascota_id' => 2,
                'empleado_id' => 2, // Dr. Carlos
                'servicio_medico_id' => 5, // Cirugía Menor
                'fecha_hora' => Carbon::now()->addDays(2)->setTime(10, 30),
                'duracion_minutos' => 90,
                'estado' => 'Programada',
                'prioridad' => 'Alta',
                'motivo_consulta' => 'Remoción de tumor cutáneo',
                'sintomas_observados' => 'Bulto en pata trasera derecha',
                'precio_estimado' => 450.00,
                'precio_final' => null,
                'observaciones' => 'Requiere ayuno previo',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0003',
                'cliente_id' => 3,
                'mascota_id' => 3,
                'empleado_id' => 3, // Dra. Lucía
                'servicio_medico_id' => 10, // Dermatología
                'fecha_hora' => Carbon::now()->addDays(3)->setTime(14, 0),
                'duracion_minutos' => 45,
                'estado' => 'Confirmada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Problemas de piel y alergias',
                'sintomas_observados' => 'Picazón excesiva, enrojecimiento',
                'precio_estimado' => 120.00,
                'precio_final' => null,
                'observaciones' => 'Posible dermatitis alérgica',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0004',
                'cliente_id' => 4,
                'mascota_id' => 4,
                'empleado_id' => 1,
                'servicio_medico_id' => 2, // Vacunación
                'fecha_hora' => Carbon::now()->subDays(1)->setTime(11, 0),
                'duracion_minutos' => 20,
                'estado' => 'Completada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Vacuna anual completa',
                'sintomas_observados' => null,
                'precio_estimado' => 65.00,
                'precio_final' => 65.00,
                'observaciones' => 'Vacunación exitosa',
                'recomendaciones' => 'Mantener en observación por 24h',
            ],
            [
                'numero_cita' => 'CITA-2025-0005',
                'cliente_id' => 5,
                'mascota_id' => 5,
                'empleado_id' => 4, // Dr. Miguel
                'servicio_medico_id' => 11, // Cardiología
                'fecha_hora' => Carbon::now()->addDays(5)->setTime(15, 30),
                'duracion_minutos' => 60,
                'estado' => 'Programada',
                'prioridad' => 'Alta',
                'motivo_consulta' => 'Soplo cardíaco detectado',
                'sintomas_observados' => 'Fatiga, dificultad respiratoria',
                'precio_estimado' => 280.00,
                'precio_final' => null,
                'observaciones' => 'Requiere electrocardiograma',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0006',
                'cliente_id' => 6,
                'mascota_id' => 6,
                'empleado_id' => 5, // Dra. Patricia
                'servicio_medico_id' => 12, // Oftalmología
                'fecha_hora' => Carbon::now()->addDays(7)->setTime(9, 45),
                'duracion_minutos' => 40,
                'estado' => 'Confirmada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Revisión ocular de rutina',
                'sintomas_observados' => 'Leve opacidad en ojo izquierdo',
                'precio_estimado' => 150.00,
                'precio_final' => null,
                'observaciones' => 'Posible inicio de cataratas',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0007',
                'cliente_id' => 7,
                'mascota_id' => 7,
                'empleado_id' => 1,
                'servicio_medico_id' => 3, // Desparasitación
                'fecha_hora' => Carbon::now()->subDays(3)->setTime(16, 15),
                'duracion_minutos' => 25,
                'estado' => 'Completada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Desparasitación preventiva',
                'sintomas_observados' => null,
                'precio_estimado' => 45.00,
                'precio_final' => 45.00,
                'observaciones' => 'Cachorro sano',
                'recomendaciones' => 'Repetir en 3 meses',
            ],
            [
                'numero_cita' => 'CITA-2025-0008',
                'cliente_id' => 8,
                'mascota_id' => 8,
                'empleado_id' => 2,
                'servicio_medico_id' => 6, // Esterilización
                'fecha_hora' => Carbon::now()->addDays(10)->setTime(8, 0),
                'duracion_minutos' => 120,
                'estado' => 'Programada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Esterilización programada',
                'sintomas_observados' => null,
                'precio_estimado' => 380.00,
                'precio_final' => null,
                'observaciones' => 'Ayuno 12 horas previo',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0009',
                'cliente_id' => 9,
                'mascota_id' => 9,
                'empleado_id' => 1,
                'servicio_medico_id' => 1,
                'fecha_hora' => Carbon::now()->subDays(5)->setTime(10, 0),
                'duracion_minutos' => 30,
                'estado' => 'Completada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Chequeo geriátrico',
                'sintomas_observados' => 'Ligera pérdida de peso',
                'precio_estimado' => 95.00,
                'precio_final' => 95.00,
                'observaciones' => 'Gato senior en buen estado',
                'recomendaciones' => 'Dieta especial para seniors',
            ],
            [
                'numero_cita' => 'CITA-2025-0010',
                'cliente_id' => 10,
                'mascota_id' => 10,
                'empleado_id' => 15, // Dr. Juan (Traumatología)
                'servicio_medico_id' => 15, // Traumatología
                'fecha_hora' => Carbon::now()->addDays(4)->setTime(13, 30),
                'duracion_minutos' => 75,
                'estado' => 'Confirmada',
                'prioridad' => 'Urgente',
                'motivo_consulta' => 'Cojera tras caída',
                'sintomas_observados' => 'No apoya pata delantera derecha',
                'precio_estimado' => 320.00,
                'precio_final' => null,
                'observaciones' => 'Posible fractura, requiere radiografías',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0011',
                'cliente_id' => 11,
                'mascota_id' => 11,
                'empleado_id' => 25, // Dr. Alberto (Medicina Felina)
                'servicio_medico_id' => 20, // Medicina Felina
                'fecha_hora' => Carbon::now()->addDays(6)->setTime(11, 15),
                'duracion_minutos' => 50,
                'estado' => 'Programada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Comportamiento agresivo reciente',
                'sintomas_observados' => 'Cambios en comportamiento, aislamiento',
                'precio_estimado' => 180.00,
                'precio_final' => null,
                'observaciones' => 'Evaluación comportamental necesaria',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0012',
                'cliente_id' => 12,
                'mascota_id' => 12,
                'empleado_id' => 1,
                'servicio_medico_id' => 1,
                'fecha_hora' => Carbon::now()->subDays(2)->setTime(14, 30),
                'duracion_minutos' => 35,
                'estado' => 'Completada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Consulta post-operatoria',
                'sintomas_observados' => 'Herida cicatrizando bien',
                'precio_estimado' => 75.00,
                'precio_final' => 75.00,
                'observaciones' => 'Recuperación satisfactoria',
                'recomendaciones' => 'Continuar con medicación 5 días más',
            ],
            [
                'numero_cita' => 'CITA-2025-0013',
                'cliente_id' => 13,
                'mascota_id' => 13,
                'empleado_id' => 16, // Dra. Isabel (Neurología)
                'servicio_medico_id' => 16, // Neurología
                'fecha_hora' => Carbon::now()->addDays(8)->setTime(10, 45),
                'duracion_minutos' => 90,
                'estado' => 'Programada',
                'prioridad' => 'Alta',
                'motivo_consulta' => 'Convulsiones recurrentes',
                'sintomas_observados' => 'Episodios de convulsiones, desorientación',
                'precio_estimado' => 420.00,
                'precio_final' => null,
                'observaciones' => 'Requiere estudios neurológicos completos',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0014',
                'cliente_id' => 14,
                'mascota_id' => 14,
                'empleado_id' => 1,
                'servicio_medico_id' => 4, // Limpieza Dental
                'fecha_hora' => Carbon::now()->addDays(12)->setTime(9, 30),
                'duracion_minutos' => 60,
                'estado' => 'Programada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Limpieza dental y revisión oral',
                'sintomas_observados' => 'Acumulación de sarro, mal aliento',
                'precio_estimado' => 250.00,
                'precio_final' => null,
                'observaciones' => 'Anestesia requerida',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0015',
                'cliente_id' => 15,
                'mascota_id' => 15,
                'empleado_id' => 1,
                'servicio_medico_id' => 13, // Medicina Exotica
                'fecha_hora' => Carbon::now()->addDays(3)->setTime(16, 0),
                'duracion_minutos' => 40,
                'estado' => 'Confirmada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Chequeo de conejo doméstico',
                'sintomas_observados' => null,
                'precio_estimado' => 110.00,
                'precio_final' => null,
                'observaciones' => 'Primera consulta para esta especie',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0016',
                'cliente_id' => 16,
                'mascota_id' => 16,
                'empleado_id' => 1,
                'servicio_medico_id' => 13,
                'fecha_hora' => Carbon::now()->addDays(9)->setTime(15, 15),
                'duracion_minutos' => 25,
                'estado' => 'Programada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Revisión de ave canaria',
                'sintomas_observados' => 'Plumaje opaco, menos canto',
                'precio_estimado' => 95.00,
                'precio_final' => null,
                'observaciones' => 'Evaluación nutricional requerida',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0017',
                'cliente_id' => 17,
                'mascota_id' => 17,
                'empleado_id' => 1,
                'servicio_medico_id' => 13,
                'fecha_hora' => Carbon::now()->subDays(4)->setTime(12, 0),
                'duracion_minutos' => 20,
                'estado' => 'Cancelada',
                'prioridad' => 'Baja',
                'motivo_consulta' => 'Chequeo de pez dorado',
                'sintomas_observados' => null,
                'precio_estimado' => 65.00,
                'precio_final' => null,
                'observaciones' => null,
                'motivo_cancelacion' => 'Cliente no pudo asistir por viaje',
            ],
            [
                'numero_cita' => 'CITA-2025-0018',
                'cliente_id' => 18,
                'mascota_id' => 18,
                'empleado_id' => 20, // Dr. Andrés (Oncología)
                'servicio_medico_id' => 17, // Oncología
                'fecha_hora' => Carbon::now()->addDays(15)->setTime(8, 30),
                'duracion_minutos' => 120,
                'estado' => 'Programada',
                'prioridad' => 'Urgente',
                'motivo_consulta' => 'Evaluación de masa abdominal',
                'sintomas_observados' => 'Pérdida de peso, letargo, masa palpable',
                'precio_estimado' => 560.00,
                'precio_final' => null,
                'observaciones' => 'Requiere biopsia y estudios de imagen',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0019',
                'cliente_id' => 19,
                'mascota_id' => 19,
                'empleado_id' => 1,
                'servicio_medico_id' => 2,
                'fecha_hora' => Carbon::now()->subDays(1)->setTime(13, 45),
                'duracion_minutos' => 25,
                'estado' => 'Completada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Primera vacunación',
                'sintomas_observados' => null,
                'precio_estimado' => 75.00,
                'precio_final' => 75.00,
                'observaciones' => 'Gatita joven muy sana',
                'recomendaciones' => 'Segunda dosis en 3 semanas',
            ],
            [
                'numero_cita' => 'CITA-2025-0020',
                'cliente_id' => 20,
                'mascota_id' => 20,
                'empleado_id' => 15,
                'servicio_medico_id' => 15,
                'fecha_hora' => Carbon::now()->addDays(14)->setTime(14, 15),
                'duracion_minutos' => 60,
                'estado' => 'Programada',
                'prioridad' => 'Alta',
                'motivo_consulta' => 'Problema de cadera',
                'sintomas_observados' => 'Dificultad para levantarse, cojera',
                'precio_estimado' => 290.00,
                'precio_final' => null,
                'observaciones' => 'Perro de raza grande con historial de displasia',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0021',
                'cliente_id' => 21,
                'mascota_id' => 21,
                'empleado_id' => 3,
                'servicio_medico_id' => 10,
                'fecha_hora' => Carbon::now()->addDays(11)->setTime(11, 30),
                'duracion_minutos' => 45,
                'estado' => 'Confirmada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Problema de piel en gato sin pelo',
                'sintomas_observados' => 'Irritación cutánea, enrojecimiento',
                'precio_estimado' => 135.00,
                'precio_final' => null,
                'observaciones' => 'Raza especial requiere cuidados particulares',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0022',
                'cliente_id' => 22,
                'mascota_id' => 22,
                'empleado_id' => 1,
                'servicio_medico_id' => 7, // Emergencia
                'fecha_hora' => Carbon::now()->subHours(2),
                'duracion_minutos' => 45,
                'estado' => 'En_Proceso',
                'prioridad' => 'Urgente',
                'motivo_consulta' => 'Atención de emergencia',
                'sintomas_observados' => 'Vómitos persistentes, deshidratación',
                'precio_estimado' => 180.00,
                'precio_final' => null,
                'observaciones' => 'Posible intoxicación alimentaria',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0023',
                'cliente_id' => 23,
                'mascota_id' => 23,
                'empleado_id' => 25,
                'servicio_medico_id' => 20,
                'fecha_hora' => Carbon::now()->addDays(13)->setTime(10, 15),
                'duracion_minutos' => 40,
                'estado' => 'Programada',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Consulta preventiva felina',
                'sintomas_observados' => null,
                'precio_estimado' => 125.00,
                'precio_final' => null,
                'observaciones' => 'Gata abisinia de exposición',
                'recomendaciones' => null,
            ],
            [
                'numero_cita' => 'CITA-2025-0024',
                'cliente_id' => 24,
                'mascota_id' => 24,
                'empleado_id' => 1,
                'servicio_medico_id' => 1,
                'fecha_hora' => Carbon::now()->subDays(6)->setTime(15, 45),
                'duracion_minutos' => 30,
                'estado' => 'No_Asistio',
                'prioridad' => 'Normal',
                'motivo_consulta' => 'Chequeo general',
                'sintomas_observados' => null,
                'precio_estimado' => 85.00,
                'precio_final' => null,
                'observaciones' => null,
                'motivo_cancelacion' => 'Cliente no se presentó a la cita',
            ],
            [
                'numero_cita' => 'CITA-2025-0025',
                'cliente_id' => 25,
                'mascota_id' => 1, // Reutilizando mascota del cliente 1
                'empleado_id' => 23, // Dra. Cristina (Anestesiología)
                'servicio_medico_id' => 18, // Anestesiología
                'fecha_hora' => Carbon::now()->addDays(16)->setTime(7, 30),
                'duracion_minutos' => 180,
                'estado' => 'Programada',
                'prioridad' => 'Alta',
                'motivo_consulta' => 'Cirugía ortopédica programada',
                'sintomas_observados' => null,
                'precio_estimado' => 850.00,
                'precio_final' => null,
                'observaciones' => 'Procedimiento quirúrgico mayor',
                'recomendaciones' => null,
            ]
        ];

        foreach ($citas as $cita) {
            DB::table('citas_medicas')->insert([
                'numero_cita' => $cita['numero_cita'],
                'cliente_id' => $cita['cliente_id'],
                'mascota_id' => $cita['mascota_id'],
                'empleado_id' => $cita['empleado_id'],
                'servicio_medico_id' => $cita['servicio_medico_id'],
                'fecha_hora' => $cita['fecha_hora'],
                'duracion_minutos' => $cita['duracion_minutos'],
                'estado' => $cita['estado'],
                'prioridad' => $cita['prioridad'],
                'motivo_consulta' => $cita['motivo_consulta'],
                'sintomas_observados' => $cita['sintomas_observados'],
                'precio_estimado' => $cita['precio_estimado'],
                'precio_final' => $cita['precio_final'] ?? null,
                'observaciones' => $cita['observaciones'],
                'recomendaciones' => $cita['recomendaciones'] ?? null,
                'fecha_reprogramacion' => null,
                'motivo_cancelacion' => $cita['motivo_cancelacion'] ?? null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
