<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('clientes')->insert([
            ['cedula' => '1710123456', 'nombre' => 'Juan Carlos', 'apellido' => 'Pérez López', 'telefono' => '0987654321', 'telefono_secundario' => '022345678', 'email' => 'juan.perez@email.com', 'direccion' => 'Av. 6 de Diciembre N26-123, Quito', 'fecha_nacimiento' => '1985-03-15', 'genero' => 'M', 'contacto_emergencia' => 'María Pérez', 'telefono_emergencia' => '0987654322', 'notas' => 'Cliente frecuente, tiene 2 perros', 'acepta_promociones' => true, 'credito_disponible' => 150.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1712345678', 'nombre' => 'María Elena', 'apellido' => 'González Torres', 'telefono' => '0976543210', 'telefono_secundario' => null, 'email' => 'maria.gonzalez@email.com', 'direccion' => 'Calle Amazonas 456, Quito', 'fecha_nacimiento' => '1990-07-22', 'genero' => 'F', 'contacto_emergencia' => 'Pedro González', 'telefono_emergencia' => '0976543211', 'notas' => null, 'acepta_promociones' => true, 'credito_disponible' => 0.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1798765432', 'nombre' => 'Carlos Alberto', 'apellido' => 'Rodríguez Silva', 'telefono' => '0965432109', 'telefono_secundario' => '023456789', 'email' => 'carlos.rodriguez@email.com', 'direccion' => 'Av. América N39-67, Quito', 'fecha_nacimiento' => '1982-11-08', 'genero' => 'M', 'contacto_emergencia' => 'Ana Rodríguez', 'telefono_emergencia' => '0965432110', 'notas' => 'Veterinario, descuento profesional', 'acepta_promociones' => false, 'credito_disponible' => 300.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1754321098', 'nombre' => 'Ana Lucía', 'apellido' => 'Martínez Herrera', 'telefono' => '0954321098', 'telefono_secundario' => null, 'email' => 'ana.martinez@email.com', 'direccion' => 'Calle García Moreno 789, Quito', 'fecha_nacimiento' => '1988-05-30', 'genero' => 'F', 'contacto_emergencia' => 'Luis Martínez', 'telefono_emergencia' => '0954321099', 'notas' => 'Tiene gatos persas de competición', 'acepta_promociones' => true, 'credito_disponible' => 75.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1743210987', 'nombre' => 'Luis Fernando', 'apellido' => 'Ramírez Castro', 'telefono' => '0943210987', 'telefono_secundario' => '024567890', 'email' => 'luis.ramirez@email.com', 'direccion' => 'Av. Eloy Alfaro N35-89, Quito', 'fecha_nacimiento' => '1975-12-03', 'genero' => 'M', 'contacto_emergencia' => 'Carmen Ramírez', 'telefono_emergencia' => '0943210988', 'notas' => 'Criador profesional de Golden Retriever', 'acepta_promociones' => true, 'credito_disponible' => 500.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1732109876', 'nombre' => 'Patricia Isabel', 'apellido' => 'Torres Morales', 'telefono' => '0932109876', 'telefono_secundario' => null, 'email' => 'patricia.torres@email.com', 'direccion' => 'Calle Colón E5-67, Quito', 'fecha_nacimiento' => '1992-04-18', 'genero' => 'F', 'contacto_emergencia' => 'Miguel Torres', 'telefono_emergencia' => '0932109877', 'notas' => null, 'acepta_promociones' => true, 'credito_disponible' => 25.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1721098765', 'nombre' => 'Miguel Ángel', 'apellido' => 'López Vargas', 'telefono' => '0921098765', 'telefono_secundario' => '025678901', 'email' => 'miguel.lopez@email.com', 'direccion' => 'Av. Portugal N26-145, Quito', 'fecha_nacimiento' => '1980-09-25', 'genero' => 'M', 'contacto_emergencia' => 'Rosa López', 'telefono_emergencia' => '0921098766', 'notas' => 'Cliente VIP, múltiples mascotas', 'acepta_promociones' => true, 'credito_disponible' => 1000.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1710987654', 'nombre' => 'Carmen Rosa', 'apellido' => 'García Mendoza', 'telefono' => '0910987654', 'telefono_secundario' => null, 'email' => 'carmen.garcia@email.com', 'direccion' => 'Calle Veintimilla 234, Quito', 'fecha_nacimiento' => '1986-01-12', 'genero' => 'F', 'contacto_emergencia' => 'Roberto García', 'telefono_emergencia' => '0910987655', 'notas' => 'Rescatista de animales abandonados', 'acepta_promociones' => false, 'credito_disponible' => 200.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1709876543', 'nombre' => 'Roberto Carlos', 'apellido' => 'Silva Jiménez', 'telefono' => '0909876543', 'telefono_secundario' => '026789012', 'email' => 'roberto.silva@email.com', 'direccion' => 'Av. Naciones Unidas E4-23, Quito', 'fecha_nacimiento' => '1977-08-07', 'genero' => 'M', 'contacto_emergencia' => 'Elena Silva', 'telefono_emergencia' => '0909876544', 'notas' => 'Dueño de tienda de mascotas', 'acepta_promociones' => true, 'credito_disponible' => 350.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1698765432', 'nombre' => 'Elena Beatriz', 'apellido' => 'Moreno Delgado', 'telefono' => '0898765432', 'telefono_secundario' => null, 'email' => 'elena.moreno@email.com', 'direccion' => 'Calle Reina Victoria N24-56, Quito', 'fecha_nacimiento' => '1993-06-14', 'genero' => 'F', 'contacto_emergencia' => 'Fernando Moreno', 'telefono_emergencia' => '0898765433', 'notas' => null, 'acepta_promociones' => true, 'credito_disponible' => 0.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1687654321', 'nombre' => 'Fernando José', 'apellido' => 'Vargas Ruiz', 'telefono' => '0887654321', 'telefono_secundario' => '027890123', 'email' => 'fernando.vargas@email.com', 'direccion' => 'Av. Mariscal Sucre S24-67, Quito', 'fecha_nacimiento' => '1984-03-09', 'genero' => 'M', 'contacto_emergencia' => 'Sofía Vargas', 'telefono_emergencia' => '0887654322', 'notas' => 'Alérgico a los gatos', 'acepta_promociones' => true, 'credito_disponible' => 120.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1676543210', 'nombre' => 'Sofía Alejandra', 'apellido' => 'Castro Peña', 'telefono' => '0876543210', 'telefono_secundario' => null, 'email' => 'sofia.castro@email.com', 'direccion' => 'Calle Juan León Mera N23-78, Quito', 'fecha_nacimiento' => '1991-10-21', 'genero' => 'F', 'contacto_emergencia' => 'Diego Castro', 'telefono_emergencia' => '0876543211', 'notas' => 'Estudiante de veterinaria', 'acepta_promociones' => true, 'credito_disponible' => 50.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1665432109', 'nombre' => 'Diego Armando', 'apellido' => 'Herrera Vega', 'telefono' => '0865432109', 'telefono_secundario' => '028901234', 'email' => 'diego.herrera@email.com', 'direccion' => 'Av. La Gasca E12-34, Quito', 'fecha_nacimiento' => '1979-12-16', 'genero' => 'M', 'contacto_emergencia' => 'Valeria Herrera', 'telefono_emergencia' => '0865432110', 'notas' => 'Tiene perros de trabajo (pastor alemán)', 'acepta_promociones' => false, 'credito_disponible' => 400.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1654321098', 'nombre' => 'Valeria Cristina', 'apellido' => 'Mendoza Romero', 'telefono' => '0854321098', 'telefono_secundario' => null, 'email' => 'valeria.mendoza@email.com', 'direccion' => 'Calle Tungurahua N26-89, Quito', 'fecha_nacimiento' => '1987-07-04', 'genero' => 'F', 'contacto_emergencia' => 'Andrea Mendoza', 'telefono_emergencia' => '0854321099', 'notas' => null, 'acepta_promociones' => true, 'credito_disponible' => 80.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1643210987', 'nombre' => 'Andrea Paola', 'apellido' => 'Espinoza Aguilar', 'telefono' => '0843210987', 'telefono_secundario' => '029012345', 'email' => 'andrea.espinoza@email.com', 'direccion' => 'Av. González Suárez N27-12, Quito', 'fecha_nacimiento' => '1989-02-28', 'genero' => 'F', 'contacto_emergencia' => 'Javier Espinoza', 'telefono_emergencia' => '0843210988', 'notas' => 'Entrenadora profesional de perros', 'acepta_promociones' => true, 'credito_disponible' => 250.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1632109876', 'nombre' => 'Javier Alejandro', 'apellido' => 'Núñez Cordova', 'telefono' => '0832109876', 'telefono_secundario' => null, 'email' => 'javier.nunez@email.com', 'direccion' => 'Calle Baquerizo Moreno E8-45, Quito', 'fecha_nacimiento' => '1983-05-13', 'genero' => 'M', 'contacto_emergencia' => 'Natalia Núñez', 'telefono_emergencia' => '0832109877', 'notas' => null, 'acepta_promociones' => true, 'credito_disponible' => 0.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1621098765', 'nombre' => 'Natalia Esperanza', 'apellido' => 'Molina Paredes', 'telefono' => '0821098765', 'telefono_secundario' => '020123456', 'email' => 'natalia.molina@email.com', 'direccion' => 'Av. 12 de Octubre N18-67, Quito', 'fecha_nacimiento' => '1994-11-06', 'genero' => 'F', 'contacto_emergencia' => 'Gabriel Molina', 'telefono_emergencia' => '0821098766', 'notas' => 'Criadora de gatos Maine Coon', 'acepta_promociones' => true, 'credito_disponible' => 180.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1610987654', 'nombre' => 'Gabriel Esteban', 'apellido' => 'Delgado Guerrero', 'telefono' => '0810987654', 'telefono_secundario' => null, 'email' => 'gabriel.delgado@email.com', 'direccion' => 'Calle Tarqui S1-23, Quito', 'fecha_nacimiento' => '1981-09-19', 'genero' => 'M', 'contacto_emergencia' => 'Isabel Delgado', 'telefono_emergencia' => '0810987655', 'notas' => 'Tiene aves exóticas', 'acepta_promociones' => false, 'credito_disponible' => 90.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1609876543', 'nombre' => 'Isabel Marcela', 'apellido' => 'Guerrero Sánchez', 'telefono' => '0809876543', 'telefono_secundario' => '021234567', 'email' => 'isabel.guerrero@email.com', 'direccion' => 'Av. Patria E4-56, Quito', 'fecha_nacimiento' => '1996-01-24', 'genero' => 'F', 'contacto_emergencia' => 'Ricardo Guerrero', 'telefono_emergencia' => '0809876544', 'notas' => null, 'acepta_promociones' => true, 'credito_disponible' => 60.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['cedula' => '1598765432', 'nombre' => 'Ricardo Emilio', 'apellido' => 'Sánchez Flores', 'telefono' => '0798765432', 'telefono_secundario' => null, 'email' => 'ricardo.sanchez@email.com', 'direccion' => 'Calle Manuela Sáenz N35-78, Quito', 'fecha_nacimiento' => '1978-06-11', 'genero' => 'M', 'contacto_emergencia' => 'Cristina Sánchez', 'telefono_emergencia' => '0798765433', 'notas' => 'Veterinario jubilado', 'acepta_promociones' => true, 'credito_disponible' => 450.00, 'activo' => true, 'created_at' => now(), 'updated_at' => now()]
        ]);
    }
}
