<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
            // Master Tables
            \App\Models\Cargo::factory(5)->create();
            \App\Models\MetodoPago::factory(5)->create();
            \App\Models\Proveedor::factory(20)->create();
            \App\Models\Producto::factory(20)->create();

            // Clientes con preferencias
            \App\Models\Cliente::factory(20)->create();
            \App\Models\Mascota::factory(20)->create();
            //
            // Modulos Recepcionista
            \App\Models\SalaEspera::factory(20)->create();
            \App\Models\Recordatorio::factory(20)->create();
            \App\Models\InteraccionCliente::factory(20)->create();
            //
            // Modulos Vendedor
            \App\Models\SesionCaja::factory(20)->create();
            \App\Models\Venta::factory(20)->create(); // Linked to sesiones, empleados
            \App\Models\Devolucion::factory(20)->create();
            \App\Models\MovimientoInventario::factory(20)->create();
            //
            // // Modulos Veterinario
            // \App\Models\ServicioMedico::factory(20)->create();
            // // Citas generated by factory logic or explicit? Factory usually linked
            // // Let's create specific standalone ones to ensure coverage
            // \App\Models\CitaMedica::factory(20)->create(); 
            // \App\Models\RegistroVacuna::factory(20)->create();
            // \App\Models\HistorialMedico::factory(20)->create();
            // \App\Models\Hospitalizacion::factory(20)->create();
            // \App\Models\Laboratorio::factory(20)->create();
    }
}
