<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HistorialesMedicosSeeder extends Seeder
{
    public function run()
    {
        $historiales = [
            [
                'mascota_id' => 1,
                'empleado_id' => 1,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-15 10:30:00',
                'peso' => 25.5,
                'temperatura' => 38.2,
                'sintomas' => 'Revisión general',
                'diagnostico' => 'Animal sano',
                'tratamiento' => 'Aplicación de vacuna antirrábica',
                'medicamentos' => null,
                'examenes_realizados' => null,
                'recomendaciones' => 'Mantener calendario de vacunas',
                'proxima_cita' => '2024-07-15',
                'observaciones' => 'Mascota en excelente estado'
            ],
            [
                'mascota_id' => 2,
                'empleado_id' => 2,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-16 11:15:00',
                'peso' => 8.2,
                'temperatura' => 38.8,
                'sintomas' => 'Problemas digestivos',
                'diagnostico' => 'Gastritis leve',
                'tratamiento' => 'Dieta blanda por 3 días',
                'medicamentos' => 'Protector gástrico',
                'examenes_realizados' => null,
                'recomendaciones' => 'Cambiar tipo de alimento',
                'proxima_cita' => '2024-01-23',
                'observaciones' => 'Mejoría progresiva'
            ],
            [
                'mascota_id' => 3,
                'empleado_id' => 1,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-17 14:20:00',
                'peso' => 15.8,
                'temperatura' => 39.1,
                'sintomas' => 'Tos persistente',
                'diagnostico' => 'Irritación respiratoria',
                'tratamiento' => 'Antibiótico por 5 días',
                'medicamentos' => 'Amoxicilina',
                'examenes_realizados' => null,
                'recomendaciones' => 'Evitar cambios bruscos de temperatura',
                'proxima_cita' => '2024-01-24',
                'observaciones' => 'Control en una semana'
            ],
            [
                'mascota_id' => 4,
                'empleado_id' => 2,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-18 09:45:00',
                'peso' => 30.2,
                'temperatura' => 38.5,
                'sintomas' => 'Cojera en pata trasera',
                'diagnostico' => 'Esguince leve',
                'tratamiento' => 'Reposo y antiinflamatorio',
                'medicamentos' => 'Carprofeno',
                'examenes_realizados' => null,
                'recomendaciones' => 'Limitación de ejercicio',
                'proxima_cita' => '2024-02-01',
                'observaciones' => 'Evitar ejercicio intenso'
            ],
            [
                'mascota_id' => 5,
                'empleado_id' => 3,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-19 16:10:00',
                'peso' => 4.5,
                'temperatura' => 38.3,
                'sintomas' => 'Problemas en la piel',
                'diagnostico' => 'Dermatitis alérgica',
                'tratamiento' => 'Champú medicado y corticoides',
                'medicamentos' => 'Prednisolona tópica',
                'examenes_realizados' => null,
                'recomendaciones' => 'Identificar alérgenos',
                'proxima_cita' => '2024-02-02',
                'observaciones' => 'Mejoría notable en 2 semanas'
            ],
            [
                'mascota_id' => 6,
                'empleado_id' => 3,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-20 13:25:00',
                'peso' => 5.8,
                'temperatura' => 38.0,
                'sintomas' => 'Pérdida de apetito',
                'diagnostico' => 'Estrés por cambio de ambiente',
                'tratamiento' => 'Estimulante del apetito',
                'medicamentos' => 'Mirtazapina',
                'examenes_realizados' => null,
                'recomendaciones' => 'Adaptar ambiente gradualmente',
                'proxima_cita' => '2024-01-27',
                'observaciones' => 'Adaptación gradual'
            ],
            [
                'mascota_id' => 7,
                'empleado_id' => 1,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-21 12:00:00',
                'peso' => 18.3,
                'temperatura' => 38.4,
                'sintomas' => 'Control postoperatorio',
                'diagnostico' => 'Recuperación satisfactoria',
                'tratamiento' => 'Curación diaria de herida',
                'medicamentos' => 'Antibiótico profiláctico',
                'examenes_realizados' => null,
                'recomendaciones' => 'Mantener área limpia',
                'proxima_cita' => '2024-01-28',
                'observaciones' => 'Cicatrización correcta'
            ],
            [
                'mascota_id' => 8,
                'empleado_id' => 2,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-22 15:30:00',
                'peso' => 22.7,
                'temperatura' => 39.2,
                'sintomas' => 'Vómitos frecuentes',
                'diagnostico' => 'Intoxicación alimentaria leve',
                'tratamiento' => 'Suero y protector gástrico',
                'medicamentos' => 'Ondansetrón',
                'examenes_realizados' => null,
                'recomendaciones' => 'Vigilar hidratación',
                'proxima_cita' => '2024-01-25',
                'observaciones' => 'Vigilar hidratación'
            ],
            [
                'mascota_id' => 9,
                'empleado_id' => 3,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-23 10:15:00',
                'peso' => 6.2,
                'temperatura' => 37.9,
                'sintomas' => 'Rigidez articular',
                'diagnostico' => 'Artrosis inicial',
                'tratamiento' => 'Condroprotector y ejercicio moderado',
                'medicamentos' => 'Glucosamina',
                'examenes_realizados' => null,
                'recomendaciones' => 'Control de peso',
                'proxima_cita' => '2024-02-23',
                'observaciones' => 'Control mensual'
            ],
            [
                'mascota_id' => 10,
                'empleado_id' => 1,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-24 11:45:00',
                'peso' => 12.4,
                'temperatura' => 38.6,
                'sintomas' => 'Herida en almohadilla',
                'diagnostico' => 'Corte superficial',
                'tratamiento' => 'Desinfección y vendaje',
                'medicamentos' => 'Betadine',
                'examenes_realizados' => null,
                'recomendaciones' => 'Evitar humedad',
                'proxima_cita' => '2024-01-31',
                'observaciones' => 'Evitar humedad'
            ],
            [
                'mascota_id' => 11,
                'empleado_id' => 3,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-25 14:50:00',
                'peso' => 4.8,
                'temperatura' => 38.1,
                'sintomas' => 'Comportamiento agresivo',
                'diagnostico' => 'Estrés territorial',
                'tratamiento' => 'Terapia conductual',
                'medicamentos' => null,
                'examenes_realizados' => null,
                'recomendaciones' => 'Separar de otros gatos',
                'proxima_cita' => '2024-02-08',
                'observaciones' => 'Separar de otros gatos'
            ],
            [
                'mascota_id' => 12,
                'empleado_id' => 2,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-26 09:20:00',
                'peso' => 28.9,
                'temperatura' => 38.7,
                'sintomas' => 'Diarrea crónica',
                'diagnostico' => 'Sensibilidad alimentaria',
                'tratamiento' => 'Dieta hipoalergénica',
                'medicamentos' => 'Probióticos',
                'examenes_realizados' => null,
                'recomendaciones' => 'Cambio gradual de alimento',
                'proxima_cita' => '2024-02-09',
                'observaciones' => 'Cambio gradual de alimento'
            ],
            [
                'mascota_id' => 13,
                'empleado_id' => 3,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-27 16:35:00',
                'peso' => 7.1,
                'temperatura' => 38.9,
                'sintomas' => 'Otitis externa',
                'diagnostico' => 'Infección bacteriana del oído',
                'tratamiento' => 'Gotas antibióticas por 7 días',
                'medicamentos' => 'Gentamicina ótica',
                'examenes_realizados' => null,
                'recomendaciones' => 'Limpiar oídos diariamente',
                'proxima_cita' => '2024-02-03',
                'observaciones' => 'Limpiar oídos diariamente'
            ],
            [
                'mascota_id' => 14,
                'empleado_id' => 1,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-28 13:10:00',
                'peso' => 35.6,
                'temperatura' => 38.3,
                'sintomas' => 'Convulsiones',
                'diagnostico' => 'Epilepsia idiopática',
                'tratamiento' => 'Anticonvulsivante diario',
                'medicamentos' => 'Fenobarbital',
                'examenes_realizados' => 'Análisis sanguíneo',
                'recomendaciones' => 'Monitoreo constante',
                'proxima_cita' => '2024-02-28',
                'observaciones' => 'Monitoreo constante'
            ],
            [
                'mascota_id' => 15,
                'empleado_id' => 3,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-29 15:40:00',
                'peso' => 3.9,
                'temperatura' => 37.8,
                'sintomas' => 'Ceguera súbita',
                'diagnostico' => 'Cataratas seniles',
                'tratamiento' => 'Evaluación oftalmológica',
                'medicamentos' => null,
                'examenes_realizados' => 'Examen oftalmológico',
                'recomendaciones' => 'Adaptar ambiente',
                'proxima_cita' => '2024-03-01',
                'observaciones' => 'Adaptar ambiente'
            ],
            [
                'mascota_id' => 16,
                'empleado_id' => 2,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-30 10:55:00',
                'peso' => 19.8,
                'temperatura' => 38.8,
                'sintomas' => 'Fractura en pata',
                'diagnostico' => 'Fractura cerrada de radio',
                'tratamiento' => 'Inmovilización con yeso',
                'medicamentos' => 'Analgésico',
                'examenes_realizados' => 'Radiografía',
                'recomendaciones' => 'Reposo absoluto 6 semanas',
                'proxima_cita' => '2024-03-15',
                'observaciones' => 'Reposo absoluto 6 semanas'
            ],
            [
                'mascota_id' => 17,
                'empleado_id' => 3,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-01-31 12:25:00',
                'peso' => 5.3,
                'temperatura' => 39.0,
                'sintomas' => 'Problemas urinarios',
                'diagnostico' => 'Cistitis bacteriana',
                'tratamiento' => 'Antibiótico y abundante agua',
                'medicamentos' => 'Cefalexina',
                'examenes_realizados' => null,
                'recomendaciones' => 'Análisis de orina en 1 semana',
                'proxima_cita' => '2024-02-07',
                'observaciones' => 'Análisis de orina en 1 semana'
            ],
            [
                'mascota_id' => 18,
                'empleado_id' => 1,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-02-01 14:15:00',
                'peso' => 26.4,
                'temperatura' => 38.1,
                'sintomas' => 'Sarro dental',
                'diagnostico' => 'Sarro dental moderado',
                'tratamiento' => 'Limpieza dental bajo anestesia',
                'medicamentos' => null,
                'examenes_realizados' => null,
                'recomendaciones' => 'Higiene dental diaria',
                'proxima_cita' => '2024-08-01',
                'observaciones' => 'Higiene dental diaria'
            ],
            [
                'mascota_id' => 19,
                'empleado_id' => 3,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-02-02 11:30:00',
                'peso' => 3.2,
                'temperatura' => 38.4,
                'sintomas' => 'Alopecia circular',
                'diagnostico' => 'Dermatofitosis (hongos)',
                'tratamiento' => 'Antifúngico tópico y oral',
                'medicamentos' => 'Ketoconazol',
                'examenes_realizados' => null,
                'recomendaciones' => 'Aislamiento temporal',
                'proxima_cita' => '2024-02-16',
                'observaciones' => 'Aislamiento temporal'
            ],
            [
                'mascota_id' => 20,
                'empleado_id' => 2,
                'cita_medica_id' => null,
                'fecha_consulta' => '2024-02-03 16:45:00',
                'peso' => 31.2,
                'temperatura' => 37.9,
                'sintomas' => 'Control geriátrico',
                'diagnostico' => 'Insuficiencia renal crónica inicial',
                'tratamiento' => 'Dieta renal y suplementos',
                'medicamentos' => 'Suplementos renales',
                'examenes_realizados' => 'Análisis sanguíneo',
                'recomendaciones' => 'Análisis sanguíneos mensuales',
                'proxima_cita' => '2024-03-03',
                'observaciones' => 'Análisis sanguíneos mensuales'
            ]
        ];

        DB::table('historiales_medicos')->insert($historiales);
    }
}
