<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MascotasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mascotas = [
            // Perros
            [
                'nombre' => 'Max',
                'especie' => 'Perro',
                'raza' => 'Golden Retriever',
                'fecha_nacimiento' => Carbon::now()->subYears(3)->subMonths(6),
                'peso' => 28.5,
                'color' => 'Dorado',
                'sexo' => 'Macho',
                'esterilizado' => true,
                'cliente_id' => 1,
                'microchip' => '982000123456789',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Luna',
                'especie' => 'Perro',
                'raza' => 'Border Collie',
                'fecha_nacimiento' => Carbon::now()->subYears(2)->subMonths(8),
                'peso' => 22.3,
                'color' => 'Negro y Blanco',
                'sexo' => 'Hembra',
                'esterilizado' => true,
                'cliente_id' => 2,
                'microchip' => '982000123456790',
                'vacunas_al_dia' => true,
                'alergias' => 'Polen',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Rocky',
                'especie' => 'Perro',
                'raza' => 'Bulldog Francés',
                'fecha_nacimiento' => Carbon::now()->subYears(4)->subMonths(2),
                'peso' => 12.8,
                'color' => 'Atigrado',
                'sexo' => 'Macho',
                'esterilizado' => false,
                'cliente_id' => 3,
                'microchip' => '982000123456791',
                'vacunas_al_dia' => true,
                'alergias' => 'Pollo',
                'condiciones_medicas' => 'Problemas respiratorios leves',
                'activo' => true,
            ],
            [
                'nombre' => 'Bella',
                'especie' => 'Perro',
                'raza' => 'Labrador Retriever',
                'fecha_nacimiento' => Carbon::now()->subYears(1)->subMonths(10),
                'peso' => 25.7,
                'color' => 'Chocolate',
                'sexo' => 'Hembra',
                'esterilizado' => false,
                'cliente_id' => 4,
                'microchip' => '982000123456792',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Charlie',
                'especie' => 'Perro',
                'raza' => 'Pastor Alemán',
                'fecha_nacimiento' => Carbon::now()->subYears(5)->subMonths(3),
                'peso' => 35.2,
                'color' => 'Negro y Marrón',
                'sexo' => 'Macho',
                'esterilizado' => true,
                'cliente_id' => 5,
                'microchip' => '982000123456793',
                'vacunas_al_dia' => true,
                'alergias' => 'Ácaros del polvo',
                'condiciones_medicas' => 'Displasia de cadera leve',
                'activo' => true,
            ],
            [
                'nombre' => 'Daisy',
                'especie' => 'Perro',
                'raza' => 'Beagle',
                'fecha_nacimiento' => Carbon::now()->subYears(3)->subMonths(1),
                'peso' => 15.4,
                'color' => 'Tricolor',
                'sexo' => 'Hembra',
                'esterilizado' => true,
                'cliente_id' => 6,
                'microchip' => '982000123456794',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Cooper',
                'especie' => 'Perro',
                'raza' => 'Cocker Spaniel',
                'fecha_nacimiento' => Carbon::now()->subMonths(8),
                'peso' => 8.9,
                'color' => 'Rubio',
                'sexo' => 'Macho',
                'esterilizado' => false,
                'cliente_id' => 7,
                'microchip' => '982000123456795',
                'vacunas_al_dia' => false,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Molly',
                'especie' => 'Perro',
                'raza' => 'Husky Siberiano',
                'fecha_nacimiento' => Carbon::now()->subYears(4)->subMonths(7),
                'peso' => 26.1,
                'color' => 'Gris y Blanco',
                'sexo' => 'Hembra',
                'esterilizado' => true,
                'cliente_id' => 8,
                'microchip' => '982000123456796',
                'vacunas_al_dia' => true,
                'alergias' => 'Soja',
                'condiciones_medicas' => null,
                'activo' => true,
            ],

            // Gatos
            [
                'nombre' => 'Whiskers',
                'especie' => 'Gato',
                'raza' => 'Persa',
                'fecha_nacimiento' => Carbon::now()->subYears(6)->subMonths(4),
                'peso' => 4.8,
                'color' => 'Blanco',
                'sexo' => 'Macho',
                'esterilizado' => true,
                'cliente_id' => 9,
                'microchip' => '982000123456797',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => 'Problemas renales crónicos',
                'activo' => true,
            ],
            [
                'nombre' => 'Mittens',
                'especie' => 'Gato',
                'raza' => 'Maine Coon',
                'fecha_nacimiento' => Carbon::now()->subYears(2)->subMonths(5),
                'peso' => 6.2,
                'color' => 'Atigrado Marrón',
                'sexo' => 'Hembra',
                'esterilizado' => true,
                'cliente_id' => 10,
                'microchip' => '982000123456798',
                'vacunas_al_dia' => true,
                'alergias' => 'Pescado',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Shadow',
                'especie' => 'Gato',
                'raza' => 'Siamés',
                'fecha_nacimiento' => Carbon::now()->subYears(3)->subMonths(9),
                'peso' => 4.1,
                'color' => 'Seal Point',
                'sexo' => 'Macho',
                'esterilizado' => true,
                'cliente_id' => 11,
                'microchip' => '982000123456799',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Fluffy',
                'especie' => 'Gato',
                'raza' => 'Ragdoll',
                'fecha_nacimiento' => Carbon::now()->subYears(1)->subMonths(6),
                'peso' => 5.5,
                'color' => 'Bicolor Azul',
                'sexo' => 'Hembra',
                'esterilizado' => false,
                'cliente_id' => 12,
                'microchip' => '982000123456800',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Tiger',
                'especie' => 'Gato',
                'raza' => 'Bengalí',
                'fecha_nacimiento' => Carbon::now()->subYears(4)->subMonths(1),
                'peso' => 5.8,
                'color' => 'Moteado Dorado',
                'sexo' => 'Macho',
                'esterilizado' => true,
                'cliente_id' => 13,
                'microchip' => '982000123456801',
                'vacunas_al_dia' => true,
                'alergias' => 'Lácteos',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Princess',
                'especie' => 'Gato',
                'raza' => 'Británico de Pelo Corto',
                'fecha_nacimiento' => Carbon::now()->subYears(7)->subMonths(2),
                'peso' => 4.9,
                'color' => 'Azul',
                'sexo' => 'Hembra',
                'esterilizado' => true,
                'cliente_id' => 14,
                'microchip' => '982000123456802',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => 'Artritis leve',
                'activo' => true,
            ],

            // Otras especies
            [
                'nombre' => 'Hoppy',
                'especie' => 'Roedor', // Cambiar de 'Conejo' a 'Roedor'
                'raza' => 'Holandés Enano',
                'fecha_nacimiento' => Carbon::now()->subYears(2)->subMonths(3),
                'peso' => 1.2,
                'color' => 'Gris y Blanco',
                'sexo' => 'Macho',
                'esterilizado' => true,
                'cliente_id' => 15,
                'microchip' => null,
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Tweety',
                'especie' => 'Ave',
                'raza' => 'Canario',
                'fecha_nacimiento' => Carbon::now()->subYears(1)->subMonths(8),
                'peso' => 0.02,
                'color' => 'Amarillo',
                'sexo' => 'Macho',
                'esterilizado' => false,
                'cliente_id' => 16,
                'microchip' => null,
                'vacunas_al_dia' => false,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Goldie',
                'especie' => 'Pez',
                'raza' => 'Goldfish',
                'fecha_nacimiento' => Carbon::now()->subMonths(10),
                'peso' => 0.05,
                'color' => 'Dorado',
                'sexo' => 'Hembra', // Cambiar de 'Indeterminado' a 'Hembra'
                'esterilizado' => false,
                'cliente_id' => 17,
                'microchip' => null,
                'vacunas_al_dia' => false,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Buddy',
                'especie' => 'Perro',
                'raza' => 'Mestizo',
                'fecha_nacimiento' => Carbon::now()->subYears(8)->subMonths(5),
                'peso' => 18.7,
                'color' => 'Negro',
                'sexo' => 'Macho',
                'esterilizado' => true,
                'cliente_id' => 18,
                'microchip' => '982000123456803',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => 'Cataratas incipientes',
                'activo' => true,
            ],
            [
                'nombre' => 'Coco',
                'especie' => 'Gato',
                'raza' => 'Común Europeo',
                'fecha_nacimiento' => Carbon::now()->subMonths(14),
                'peso' => 3.8,
                'color' => 'Negro y Blanco',
                'sexo' => 'Hembra',
                'esterilizado' => false,
                'cliente_id' => 19,
                'microchip' => '982000123456804',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Zeus',
                'especie' => 'Perro',
                'raza' => 'Rottweiler',
                'fecha_nacimiento' => Carbon::now()->subYears(6)->subMonths(8),
                'peso' => 42.5,
                'color' => 'Negro y Marrón',
                'sexo' => 'Macho',
                'esterilizado' => true,
                'cliente_id' => 20,
                'microchip' => '982000123456805',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => 'Displasia de codo',
                'activo' => true,
            ],
            [
                'nombre' => 'Mia',
                'especie' => 'Gato',
                'raza' => 'Esfinge',
                'fecha_nacimiento' => Carbon::now()->subYears(3)->subMonths(7),
                'peso' => 3.5,
                'color' => 'Rosa',
                'sexo' => 'Hembra',
                'esterilizado' => true,
                'cliente_id' => 21,
                'microchip' => '982000123456806',
                'vacunas_al_dia' => true,
                'alergias' => 'Protección solar requerida',
                'condiciones_medicas' => 'Piel sensible',
                'activo' => true,
            ],
            [
                'nombre' => 'Rex',
                'especie' => 'Perro',
                'raza' => 'Doberman',
                'fecha_nacimiento' => Carbon::now()->subYears(4)->subMonths(11),
                'peso' => 38.2,
                'color' => 'Negro y Fuego',
                'sexo' => 'Macho',
                'esterilizado' => true,
                'cliente_id' => 22,
                'microchip' => '982000123456807',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Nala',
                'especie' => 'Gato',
                'raza' => 'Abisinio',
                'fecha_nacimiento' => Carbon::now()->subYears(2)->subMonths(1),
                'peso' => 4.3,
                'color' => 'Leonado',
                'sexo' => 'Hembra',
                'esterilizado' => true,
                'cliente_id' => 23,
                'microchip' => '982000123456808',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Toby',
                'especie' => 'Perro',
                'raza' => 'Jack Russell Terrier',
                'fecha_nacimiento' => Carbon::now()->subYears(5)->subMonths(6),
                'peso' => 7.8,
                'color' => 'Blanco y Marrón',
                'sexo' => 'Macho',
                'esterilizado' => true,
                'cliente_id' => 24,
                'microchip' => '982000123456809',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Kira',
                'especie' => 'Perro',
                'raza' => 'Pastor Belga',
                'fecha_nacimiento' => Carbon::now()->subYears(3)->subMonths(8),
                'peso' => 22.5,
                'color' => 'Negro',
                'sexo' => 'Hembra',
                'esterilizado' => true,
                'cliente_id' => 20,
                'microchip' => '982000123456810',
                'vacunas_al_dia' => true,
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'activo' => true,
            ]
        ];

        foreach ($mascotas as $index => $mascota) {
            DB::table('mascotas')->insert([
                'codigo_mascota' => 'MASC' . str_pad($index + 1, 4, '0', STR_PAD_LEFT),
                'nombre' => $mascota['nombre'],
                'especie' => $mascota['especie'],
                'raza' => $mascota['raza'],
                'fecha_nacimiento' => $mascota['fecha_nacimiento'],
                'peso' => $mascota['peso'],
                'color' => $mascota['color'],
                'sexo' => $mascota['sexo'],
                'esterilizado' => $mascota['esterilizado'],
                'cliente_id' => $mascota['cliente_id'],
                'microchip' => $mascota['microchip'],
                'alergias' => $mascota['alergias'],
                'condiciones_medicas' => $mascota['condiciones_medicas'],
                'activo' => $mascota['activo'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
