<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MovimientosStockSeeder extends Seeder
{
    public function run()
    {
        $movimientos = [
            [
                'producto_id' => 1,
                'empleado_id' => 1,
                'venta_id' => null,
                'tipo_movimiento' => 'Entrada',
                'cantidad' => 30,
                'stock_anterior' => 50,
                'stock_nuevo' => 80,
                'precio_unitario' => 15.50,
                'motivo' => 'Compra de alimento balanceado',
                'numero_factura_compra' => 'FC001',
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-15 08:00:00',
                'updated_at' => '2024-01-15 08:00:00'
            ],
            [
                'producto_id' => 1,
                'empleado_id' => 1,
                'venta_id' => 1,
                'tipo_movimiento' => 'Salida',
                'cantidad' => -5,
                'stock_anterior' => 80,
                'stock_nuevo' => 75,
                'precio_unitario' => null,
                'motivo' => 'Venta de alimento',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-20 10:30:00',
                'updated_at' => '2024-01-20 10:30:00'
            ],
            [
                'producto_id' => 2,
                'empleado_id' => 1,
                'venta_id' => null,
                'tipo_movimiento' => 'Entrada',
                'cantidad' => 20,
                'stock_anterior' => 25,
                'stock_nuevo' => 45,
                'precio_unitario' => 8.75,
                'motivo' => 'Compra de vitaminas',
                'numero_factura_compra' => 'FC002',
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-16 09:15:00',
                'updated_at' => '2024-01-16 09:15:00'
            ],
            [
                'producto_id' => 2,
                'empleado_id' => 2,
                'venta_id' => 2,
                'tipo_movimiento' => 'Salida',
                'cantidad' => -3,
                'stock_anterior' => 45,
                'stock_nuevo' => 42,
                'precio_unitario' => null,
                'motivo' => 'Venta de vitaminas',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-21 11:15:00',
                'updated_at' => '2024-01-21 11:15:00'
            ],
            [
                'producto_id' => 3,
                'empleado_id' => 2,
                'venta_id' => null,
                'tipo_movimiento' => 'Entrada',
                'cantidad' => 15,
                'stock_anterior' => 10,
                'stock_nuevo' => 25,
                'precio_unitario' => 12.30,
                'motivo' => 'Compra de juguetes',
                'numero_factura_compra' => 'FC003',
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-17 10:30:00',
                'updated_at' => '2024-01-17 10:30:00'
            ],
            [
                'producto_id' => 3,
                'empleado_id' => 1,
                'venta_id' => 3,
                'tipo_movimiento' => 'Salida',
                'cantidad' => -2,
                'stock_anterior' => 25,
                'stock_nuevo' => 23,
                'precio_unitario' => null,
                'motivo' => 'Venta de juguetes',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-22 12:45:00',
                'updated_at' => '2024-01-22 12:45:00'
            ],
            [
                'producto_id' => 4,
                'empleado_id' => 2,
                'venta_id' => null,
                'tipo_movimiento' => 'Entrada',
                'cantidad' => 25,
                'stock_anterior' => 15,
                'stock_nuevo' => 40,
                'precio_unitario' => 6.80,
                'motivo' => 'Compra de arena sanitaria',
                'numero_factura_compra' => 'FC004',
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-18 11:45:00',
                'updated_at' => '2024-01-18 11:45:00'
            ],
            [
                'producto_id' => 4,
                'empleado_id' => 2,
                'venta_id' => 4,
                'tipo_movimiento' => 'Salida',
                'cantidad' => -8,
                'stock_anterior' => 40,
                'stock_nuevo' => 32,
                'precio_unitario' => null,
                'motivo' => 'Venta de arena sanitaria',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-23 13:30:00',
                'updated_at' => '2024-01-23 13:30:00'
            ],
            [
                'producto_id' => 5,
                'empleado_id' => 1,
                'venta_id' => null,
                'tipo_movimiento' => 'Entrada',
                'cantidad' => 12,
                'stock_anterior' => 8,
                'stock_nuevo' => 20,
                'precio_unitario' => 18.90,
                'motivo' => 'Compra de collares',
                'numero_factura_compra' => 'FC005',
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-19 14:20:00',
                'updated_at' => '2024-01-19 14:20:00'
            ],
            [
                'producto_id' => 5,
                'empleado_id' => 1,
                'venta_id' => 5,
                'tipo_movimiento' => 'Salida',
                'cantidad' => -4,
                'stock_anterior' => 20,
                'stock_nuevo' => 16,
                'precio_unitario' => null,
                'motivo' => 'Venta de collares',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-24 14:15:00',
                'updated_at' => '2024-01-24 14:15:00'
            ],
            [
                'producto_id' => 6,
                'empleado_id' => 2,
                'venta_id' => null,
                'tipo_movimiento' => 'Entrada',
                'cantidad' => 18,
                'stock_anterior' => 12,
                'stock_nuevo' => 30,
                'precio_unitario' => 22.50,
                'motivo' => 'Compra de correas',
                'numero_factura_compra' => 'FC006',
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-25 08:30:00',
                'updated_at' => '2024-01-25 08:30:00'
            ],
            [
                'producto_id' => 6,
                'empleado_id' => 1,
                'venta_id' => 6,
                'tipo_movimiento' => 'Salida',
                'cantidad' => -3,
                'stock_anterior' => 30,
                'stock_nuevo' => 27,
                'precio_unitario' => null,
                'motivo' => 'Venta de correas',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-28 11:00:00',
                'updated_at' => '2024-01-28 11:00:00'
            ],
            [
                'producto_id' => 7,
                'empleado_id' => 1,
                'venta_id' => null,
                'tipo_movimiento' => 'Entrada',
                'cantidad' => 22,
                'stock_anterior' => 8,
                'stock_nuevo' => 30,
                'precio_unitario' => 14.25,
                'motivo' => 'Compra de champú',
                'numero_factura_compra' => 'FC007',
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-26 09:45:00',
                'updated_at' => '2024-01-26 09:45:00'
            ],
            [
                'producto_id' => 7,
                'empleado_id' => 2,
                'venta_id' => 7,
                'tipo_movimiento' => 'Salida',
                'cantidad' => -2,
                'stock_anterior' => 30,
                'stock_nuevo' => 28,
                'precio_unitario' => null,
                'motivo' => 'Venta de champú',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-29 12:30:00',
                'updated_at' => '2024-01-29 12:30:00'
            ],
            [
                'producto_id' => 8,
                'empleado_id' => 2,
                'venta_id' => null,
                'tipo_movimiento' => 'Entrada',
                'cantidad' => 16,
                'stock_anterior' => 14,
                'stock_nuevo' => 30,
                'precio_unitario' => 35.75,
                'motivo' => 'Compra de medicamentos',
                'numero_factura_compra' => 'FC008',
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-27 10:20:00',
                'updated_at' => '2024-01-27 10:20:00'
            ],
            [
                'producto_id' => 8,
                'empleado_id' => 1,
                'venta_id' => 8,
                'tipo_movimiento' => 'Salida',
                'cantidad' => -1,
                'stock_anterior' => 30,
                'stock_nuevo' => 29,
                'precio_unitario' => null,
                'motivo' => 'Venta de medicamentos',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-01-30 13:15:00',
                'updated_at' => '2024-01-30 13:15:00'
            ],
            [
                'producto_id' => 1,
                'empleado_id' => 1,
                'venta_id' => null,
                'tipo_movimiento' => 'Ajuste',
                'cantidad' => -2,
                'stock_anterior' => 75,
                'stock_nuevo' => 73,
                'precio_unitario' => null,
                'motivo' => 'Ajuste por inventario físico',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => 'Diferencia encontrada en inventario',
                'created_at' => '2024-01-31 16:00:00',
                'updated_at' => '2024-01-31 16:00:00'
            ],
            [
                'producto_id' => 2,
                'empleado_id' => 2,
                'venta_id' => null,
                'tipo_movimiento' => 'Ajuste',
                'cantidad' => 1,
                'stock_anterior' => 42,
                'stock_nuevo' => 43,
                'precio_unitario' => null,
                'motivo' => 'Ajuste por error de registro',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => 'Corrección de error contable',
                'created_at' => '2024-02-01 08:45:00',
                'updated_at' => '2024-02-01 08:45:00'
            ],
            [
                'producto_id' => 3,
                'empleado_id' => 1,
                'venta_id' => null,
                'tipo_movimiento' => 'Devolucion',
                'cantidad' => 1,
                'stock_anterior' => 23,
                'stock_nuevo' => 24,
                'precio_unitario' => null,
                'motivo' => 'Devolución por defecto del cliente',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => 'Cliente devolvió producto defectuoso',
                'created_at' => '2024-02-02 09:30:00',
                'updated_at' => '2024-02-02 09:30:00'
            ],
            [
                'producto_id' => 9,
                'empleado_id' => 2,
                'venta_id' => null,
                'tipo_movimiento' => 'Entrada',
                'cantidad' => 20,
                'stock_anterior' => 5,
                'stock_nuevo' => 25,
                'precio_unitario' => 85.00,
                'motivo' => 'Compra de transportadoras',
                'numero_factura_compra' => 'FC009',
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-02-03 10:15:00',
                'updated_at' => '2024-02-03 10:15:00'
            ],
            [
                'producto_id' => 9,
                'empleado_id' => 2,
                'venta_id' => 9,
                'tipo_movimiento' => 'Salida',
                'cantidad' => -1,
                'stock_anterior' => 25,
                'stock_nuevo' => 24,
                'precio_unitario' => null,
                'motivo' => 'Venta de transportadora',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-02-05 12:30:00',
                'updated_at' => '2024-02-05 12:30:00'
            ],
            [
                'producto_id' => 10,
                'empleado_id' => 1,
                'venta_id' => null,
                'tipo_movimiento' => 'Entrada',
                'cantidad' => 30,
                'stock_anterior' => 10,
                'stock_nuevo' => 40,
                'precio_unitario' => 9.50,
                'motivo' => 'Compra de platos y bebederos',
                'numero_factura_compra' => 'FC010',
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-02-04 11:00:00',
                'updated_at' => '2024-02-04 11:00:00'
            ],
            [
                'producto_id' => 10,
                'empleado_id' => 1,
                'venta_id' => 10,
                'tipo_movimiento' => 'Salida',
                'cantidad' => -6,
                'stock_anterior' => 40,
                'stock_nuevo' => 34,
                'precio_unitario' => null,
                'motivo' => 'Venta de platos y bebederos',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-02-06 13:45:00',
                'updated_at' => '2024-02-06 13:45:00'
            ],
            [
                'producto_id' => 4,
                'empleado_id' => 2,
                'venta_id' => 11,
                'tipo_movimiento' => 'Salida',
                'cantidad' => -5,
                'stock_anterior' => 32,
                'stock_nuevo' => 27,
                'precio_unitario' => null,
                'motivo' => 'Venta de arena sanitaria',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-02-07 14:20:00',
                'updated_at' => '2024-02-07 14:20:00'
            ],
            [
                'producto_id' => 1,
                'empleado_id' => 1,
                'venta_id' => 12,
                'tipo_movimiento' => 'Salida',
                'cantidad' => -10,
                'stock_anterior' => 73,
                'stock_nuevo' => 63,
                'precio_unitario' => null,
                'motivo' => 'Venta de alimento balanceado',
                'numero_factura_compra' => null,
                'lote' => null,
                'fecha_vencimiento' => null,
                'observaciones' => null,
                'created_at' => '2024-02-08 15:10:00',
                'updated_at' => '2024-02-08 15:10:00'
            ]
        ];

        DB::table('movimientos_stock')->insert($movimientos);
    }
}
