<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PromocionesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $promociones = [
            [
                'codigo' => 'NUEVOCL20',
                'nombre' => 'Descuento Nuevo Cliente',
                'descripcion' => '20% de descuento para clientes nuevos en su primera consulta',
                'tipo_descuento' => 'porcentaje',
                'valor_descuento' => 20.00,
                'fecha_inicio' => Carbon::now()->subDays(30),
                'fecha_fin' => Carbon::now()->addMonths(6),
                'limite_usos' => null,
                'usos_actuales' => 0,
                'monto_minimo' => 50.00,
                'activo' => true,
            ],
            [
                'codigo' => 'VACUNA15',
                'nombre' => 'Promoción Vacunación',
                'descripcion' => '15% de descuento en todas las vacunas',
                'tipo_descuento' => 'porcentaje',
                'valor_descuento' => 15.00,
                'fecha_inicio' => Carbon::now()->subDays(15),
                'fecha_fin' => Carbon::now()->addMonths(3),
                'limite_usos' => 200,
                'usos_actuales' => 45,
                'monto_minimo' => 30.00,
                'activo' => true,
            ],
            [
                'codigo' => 'ESTER100',
                'nombre' => 'Castración/Esterilización',
                'descripcion' => '$100 de descuento en cirugías de esterilización',
                'tipo_descuento' => 'fijo',
                'valor_descuento' => 100.00,
                'fecha_inicio' => Carbon::now()->subDays(10),
                'fecha_fin' => Carbon::now()->addMonths(4),
                'limite_usos' => 50,
                'usos_actuales' => 12,
                'monto_minimo' => 300.00,
                'activo' => true,
            ],
            [
                'codigo' => 'MASCOTAS2X1',
                'nombre' => 'Consulta 2x1 Mascotas',
                'descripcion' => 'Segunda consulta gratis para la segunda mascota del mismo dueño',
                'tipo_descuento' => 'porcentaje',
                'valor_descuento' => 50.00,
                'fecha_inicio' => Carbon::now()->subDays(20),
                'fecha_fin' => Carbon::now()->addMonths(2),
                'limite_usos' => 100,
                'usos_actuales' => 23,
                'monto_minimo' => 80.00,
                'activo' => true,
            ],
            [
                'codigo' => 'ALIMENTO25',
                'nombre' => 'Descuento Alimentos',
                'descripcion' => '25% de descuento en alimentos premium de 15kg o más',
                'tipo_descuento' => 'porcentaje',
                'valor_descuento' => 25.00,
                'fecha_inicio' => Carbon::now()->subDays(5),
                'fecha_fin' => Carbon::now()->addMonths(1),
                'limite_usos' => 300,
                'usos_actuales' => 67,
                'monto_minimo' => 60.00,
                'activo' => true,
            ],
            [
                'codigo' => 'SENIOR10',
                'nombre' => 'Descuento Adultos Mayores',
                'descripcion' => '10% de descuento para clientes mayores de 65 años',
                'tipo_descuento' => 'porcentaje',
                'valor_descuento' => 10.00,
                'fecha_inicio' => Carbon::now()->subMonths(1),
                'fecha_fin' => Carbon::now()->addMonths(12),
                'limite_usos' => null,
                'usos_actuales' => 34,
                'monto_minimo' => 40.00,
                'activo' => true,
            ],
            [
                'codigo' => 'VERANO50',
                'nombre' => 'Promo Verano Antipulgas',
                'descripcion' => '$50 de descuento en tratamientos antipulgas y garrapatas',
                'tipo_descuento' => 'fijo',
                'valor_descuento' => 50.00,
                'fecha_inicio' => Carbon::now()->subDays(45),
                'fecha_fin' => Carbon::now()->addDays(30),
                'limite_usos' => 150,
                'usos_actuales' => 89,
                'monto_minimo' => 120.00,
                'activo' => true,
            ],
            [
                'codigo' => 'NAVIDAD30',
                'nombre' => 'Promoción Navideña',
                'descripcion' => '30% de descuento en accesorios y juguetes',
                'tipo_descuento' => 'porcentaje',
                'valor_descuento' => 30.00,
                'fecha_inicio' => Carbon::parse('2025-12-01'),
                'fecha_fin' => Carbon::parse('2025-12-31'),
                'limite_usos' => 500,
                'usos_actuales' => 126,
                'monto_minimo' => 25.00,
                'activo' => true,
            ],
            [
                'codigo' => 'COMPRA200',
                'nombre' => 'Descuento por Volumen',
                'descripcion' => '$75 de descuento en compras mayores a $200',
                'tipo_descuento' => 'fijo',
                'valor_descuento' => 75.00,
                'fecha_inicio' => Carbon::now()->subDays(60),
                'fecha_fin' => Carbon::now()->addMonths(6),
                'limite_usos' => null,
                'usos_actuales' => 78,
                'monto_minimo' => 200.00,
                'activo' => true,
            ],
            [
                'codigo' => 'DENTAL20',
                'nombre' => 'Promoción Salud Dental',
                'descripcion' => '20% de descuento en limpiezas dentales y productos de higiene oral',
                'tipo_descuento' => 'porcentaje',
                'valor_descuento' => 20.00,
                'fecha_inicio' => Carbon::now()->subDays(25),
                'fecha_fin' => Carbon::now()->addMonths(2),
                'limite_usos' => 80,
                'usos_actuales' => 31,
                'monto_minimo' => 90.00,
                'activo' => true,
            ],
            [
                'codigo' => 'FIDELIDAD15',
                'nombre' => 'Cliente Fiel',
                'descripcion' => '15% de descuento para clientes con más de 10 consultas',
                'tipo_descuento' => 'porcentaje',
                'valor_descuento' => 15.00,
                'fecha_inicio' => Carbon::now()->subMonths(2),
                'fecha_fin' => Carbon::now()->addMonths(12),
                'limite_usos' => null,
                'usos_actuales' => 156,
                'monto_minimo' => 50.00,
                'activo' => true,
            ],
            [
                'codigo' => 'EMERGENCIA40',
                'nombre' => 'Ayuda Emergencia',
                'descripcion' => '$40 de descuento en consultas de emergencia los fines de semana',
                'tipo_descuento' => 'fijo',
                'valor_descuento' => 40.00,
                'fecha_inicio' => Carbon::now()->subDays(90),
                'fecha_fin' => Carbon::now()->addMonths(3),
                'limite_usos' => 60,
                'usos_actuales' => 23,
                'monto_minimo' => 150.00,
                'activo' => true,
            ],
            [
                'codigo' => 'GATOS12',
                'nombre' => 'Especialidad Felina',
                'descripcion' => '12% de descuento en consultas especializadas para gatos',
                'tipo_descuento' => 'porcentaje',
                'valor_descuento' => 12.00,
                'fecha_inicio' => Carbon::now()->subDays(40),
                'fecha_fin' => Carbon::now()->addMonths(4),
                'limite_usos' => 120,
                'usos_actuales' => 67,
                'monto_minimo' => 70.00,
                'activo' => true,
            ],
            [
                'codigo' => 'REFERIDOS25',
                'nombre' => 'Programa Referidos',
                'descripcion' => '$25 de descuento por cada cliente referido que realice una compra',
                'tipo_descuento' => 'fijo',
                'valor_descuento' => 25.00,
                'fecha_inicio' => Carbon::now()->subMonths(1),
                'fecha_fin' => Carbon::now()->addMonths(8),
                'limite_usos' => null,
                'usos_actuales' => 89,
                'monto_minimo' => 75.00,
                'activo' => true,
            ],
            [
                'codigo' => 'CIRUGIA150',
                'nombre' => 'Descuento Cirugías',
                'descripcion' => '$150 de descuento en cirugías mayores',
                'tipo_descuento' => 'fijo',
                'valor_descuento' => 150.00,
                'fecha_inicio' => Carbon::now()->subDays(14),
                'fecha_fin' => Carbon::now()->addMonths(5),
                'limite_usos' => 25,
                'usos_actuales' => 8,
                'monto_minimo' => 500.00,
                'activo' => true,
            ],
            [
                'codigo' => 'MICROCHIP30',
                'nombre' => 'Promoción Microchip',
                'descripcion' => '$30 de descuento en colocación de microchip',
                'tipo_descuento' => 'fijo',
                'valor_descuento' => 30.00,
                'fecha_inicio' => Carbon::now()->subDays(35),
                'fecha_fin' => Carbon::now()->addMonths(3),
                'limite_usos' => 100,
                'usos_actuales' => 42,
                'monto_minimo' => 80.00,
                'activo' => true,
            ],
            [
                'codigo' => 'SUPLEMENT18',
                'nombre' => 'Vitaminas y Suplementos',
                'descripcion' => '18% de descuento en vitaminas y suplementos nutricionales',
                'tipo_descuento' => 'porcentaje',
                'valor_descuento' => 18.00,
                'fecha_inicio' => Carbon::now()->subDays(50),
                'fecha_fin' => Carbon::now()->addMonths(2),
                'limite_usos' => 200,
                'usos_actuales' => 93,
                'monto_minimo' => 45.00,
                'activo' => true,
            ],
            [
                'codigo' => 'ANIVERSARIO50',
                'nombre' => 'Aniversario Clínica',
                'descripcion' => '$50 de descuento por aniversario de la clínica',
                'tipo_descuento' => 'fijo',
                'valor_descuento' => 50.00,
                'fecha_inicio' => Carbon::parse('2025-01-15'),
                'fecha_fin' => Carbon::parse('2025-01-31'),
                'limite_usos' => 300,
                'usos_actuales' => 287,
                'monto_minimo' => 100.00,
                'activo' => false,
            ],
            [
                'codigo' => 'DESCACHORRO22',
                'nombre' => 'Paquete Cachorro',
                'descripcion' => '22% de descuento en paquete completo para cachorros (vacunas + desparasitación)',
                'tipo_descuento' => 'porcentaje',
                'valor_descuento' => 22.00,
                'fecha_inicio' => Carbon::now()->subDays(30),
                'fecha_fin' => Carbon::now()->addMonths(6),
                'limite_usos' => 150,
                'usos_actuales' => 76,
                'monto_minimo' => 120.00,
                'activo' => true,
            ],
            [
                'codigo' => 'LABORATORIO35',
                'nombre' => 'Promoción Laboratorio',
                'descripcion' => '$35 de descuento en exámenes de laboratorio completos',
                'tipo_descuento' => 'fijo',
                'valor_descuento' => 35.00,
                'fecha_inicio' => Carbon::now()->subDays(20),
                'fecha_fin' => Carbon::now()->addMonths(3),
                'limite_usos' => 80,
                'usos_actuales' => 34,
                'monto_minimo' => 150.00,
                'activo' => true,
            ]
        ];

        foreach ($promociones as $promocion) {
            DB::table('promociones')->insert([
                'codigo' => $promocion['codigo'],
                'nombre' => $promocion['nombre'],
                'descripcion' => $promocion['descripcion'],
                'tipo_descuento' => $promocion['tipo_descuento'],
                'valor_descuento' => $promocion['valor_descuento'],
                'fecha_inicio' => $promocion['fecha_inicio'],
                'fecha_fin' => $promocion['fecha_fin'],
                'limite_usos' => $promocion['limite_usos'],
                'usos_actuales' => $promocion['usos_actuales'],
                'monto_minimo' => $promocion['monto_minimo'],
                'activo' => $promocion['activo'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
