<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PromocionesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $promociones = [
            [
                'nombre' => 'Descuento Nuevo Cliente',
                'descripcion' => '20% de descuento para clientes nuevos en su primera consulta',
                'tipo' => 'Porcentaje',
                'valor' => 20.00,
                'fecha_inicio' => Carbon::now()->subDays(30),
                'fecha_fin' => Carbon::now()->addMonths(6),
                'usos_maximos' => null,
                'usos_por_cliente' => 1,
                'monto_minimo' => 50.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Descuento Mascotas Senior',
                'descripcion' => '15% de descuento en consultas para mascotas mayores de 8 años',
                'tipo' => 'Porcentaje',
                'valor' => 15.00,
                'fecha_inicio' => Carbon::now()->subDays(60),
                'fecha_fin' => Carbon::now()->addMonths(12),
                'usos_maximos' => 500,
                'usos_por_cliente' => 3,
                'monto_minimo' => 30.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Pack Vacunación',
                'descripcion' => '$25 de descuento en pack completo de vacunación',
                'tipo' => 'Monto_Fijo',
                'valor' => 25.00,
                'fecha_inicio' => Carbon::now()->subDays(15),
                'fecha_fin' => Carbon::now()->addMonths(3),
                'usos_maximos' => 200,
                'usos_por_cliente' => 2,
                'monto_minimo' => 100.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Consulta Gratis Segunda Mascota',
                'descripcion' => 'Consulta veterinaria gratuita para la segunda mascota',
                'tipo' => 'Servicio_Gratis',
                'valor' => 45.00,
                'fecha_inicio' => Carbon::now()->subDays(45),
                'fecha_fin' => Carbon::now()->addMonths(4),
                'usos_maximos' => 150,
                'usos_por_cliente' => 1,
                'monto_minimo' => 80.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Black Friday Pet',
                'descripcion' => '30% de descuento en todos los servicios médicos',
                'tipo' => 'Porcentaje',
                'valor' => 30.00,
                'fecha_inicio' => Carbon::now()->subDays(90),
                'fecha_fin' => Carbon::now()->subDays(85),
                'usos_maximos' => 1000,
                'usos_por_cliente' => 1,
                'monto_minimo' => 20.00,
                'activa' => false,
            ],
            [
                'nombre' => 'Descuento Estudiantes',
                'descripcion' => '10% de descuento para estudiantes de veterinaria',
                'tipo' => 'Porcentaje',
                'valor' => 10.00,
                'fecha_inicio' => Carbon::now()->subDays(120),
                'fecha_fin' => Carbon::now()->addMonths(8),
                'usos_maximos' => 300,
                'usos_por_cliente' => 2,
                'monto_minimo' => 25.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Castración Solidaria',
                'descripcion' => '$40 de descuento en procedimientos de castración',
                'tipo' => 'Monto_Fijo',
                'valor' => 40.00,
                'fecha_inicio' => Carbon::now()->subDays(20),
                'fecha_fin' => Carbon::now()->addMonths(2),
                'usos_maximos' => 100,
                'usos_por_cliente' => 1,
                'monto_minimo' => 120.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Mes del Gato',
                'descripcion' => '25% de descuento en servicios para felinos',
                'tipo' => 'Porcentaje',
                'valor' => 25.00,
                'fecha_inicio' => Carbon::now()->addDays(15),
                'fecha_fin' => Carbon::now()->addDays(45),
                'usos_maximos' => 250,
                'usos_por_cliente' => 2,
                'monto_minimo' => 35.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Limpieza Dental Promo',
                'descripcion' => '$30 de descuento en limpieza dental',
                'tipo' => 'Monto_Fijo',
                'valor' => 30.00,
                'fecha_inicio' => Carbon::now()->subDays(10),
                'fecha_fin' => Carbon::now()->addMonths(5),
                'usos_maximos' => 80,
                'usos_por_cliente' => 1,
                'monto_minimo' => 150.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Cliente Frecuente',
                'descripcion' => '12% de descuento para clientes con más de 5 visitas',
                'tipo' => 'Porcentaje',
                'valor' => 12.00,
                'fecha_inicio' => Carbon::now()->subDays(180),
                'fecha_fin' => Carbon::now()->addMonths(12),
                'usos_maximos' => null,
                'usos_por_cliente' => 10,
                'monto_minimo' => 40.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Promo Fin de Semana',
                'descripcion' => '8% de descuento en consultas de fin de semana',
                'tipo' => 'Porcentaje',
                'valor' => 8.00,
                'fecha_inicio' => Carbon::now()->subDays(7),
                'fecha_fin' => Carbon::now()->addMonths(1),
                'usos_maximos' => 400,
                'usos_por_cliente' => 4,
                'monto_minimo' => 20.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Adopción Responsable',
                'descripcion' => 'Primera consulta gratuita para mascotas adoptadas',
                'tipo' => 'Servicio_Gratis',
                'valor' => 45.00,
                'fecha_inicio' => Carbon::now()->subDays(30),
                'fecha_fin' => Carbon::now()->addMonths(6),
                'usos_maximos' => 200,
                'usos_por_cliente' => 1,
                'monto_minimo' => 0.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Emergencia 24h Descuento',
                'descripcion' => '$20 de descuento en consultas de emergencia nocturna',
                'tipo' => 'Monto_Fijo',
                'valor' => 20.00,
                'fecha_inicio' => Carbon::now()->subDays(5),
                'fecha_fin' => Carbon::now()->addMonths(3),
                'usos_maximos' => 150,
                'usos_por_cliente' => 2,
                'monto_minimo' => 80.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Descuento Tercera Edad',
                'descripcion' => '18% de descuento para propietarios mayores de 65 años',
                'tipo' => 'Porcentaje',
                'valor' => 18.00,
                'fecha_inicio' => Carbon::now()->subDays(100),
                'fecha_fin' => Carbon::now()->addMonths(10),
                'usos_maximos' => null,
                'usos_por_cliente' => 5,
                'monto_minimo' => 30.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Combo Desparasitación',
                'descripcion' => '$15 de descuento en desparasitación interna y externa',
                'tipo' => 'Monto_Fijo',
                'valor' => 15.00,
                'fecha_inicio' => Carbon::now()->subDays(25),
                'fecha_fin' => Carbon::now()->addMonths(4),
                'usos_maximos' => 300,
                'usos_por_cliente' => 3,
                'monto_minimo' => 60.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Referido Amigo',
                'descripcion' => '22% de descuento por referir un nuevo cliente',
                'tipo' => 'Porcentaje',
                'valor' => 22.00,
                'fecha_inicio' => Carbon::now()->subDays(50),
                'fecha_fin' => Carbon::now()->addMonths(8),
                'usos_maximos' => 500,
                'usos_por_cliente' => 3,
                'monto_minimo' => 50.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Chequeo Anual Completo',
                'descripcion' => '$35 de descuento en chequeo médico anual',
                'tipo' => 'Monto_Fijo',
                'valor' => 35.00,
                'fecha_inicio' => Carbon::now()->subDays(15),
                'fecha_fin' => Carbon::now()->addMonths(6),
                'usos_maximos' => 120,
                'usos_por_cliente' => 1,
                'monto_minimo' => 200.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Micro-chip Identificación',
                'descripcion' => '$12 de descuento en colocación de micro-chip',
                'tipo' => 'Monto_Fijo',
                'valor' => 12.00,
                'fecha_inicio' => Carbon::now()->subDays(40),
                'fecha_fin' => Carbon::now()->addMonths(5),
                'usos_maximos' => 200,
                'usos_por_cliente' => 2,
                'monto_minimo' => 50.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Descuento Múltiples Mascotas',
                'descripcion' => '14% de descuento para propietarios con 3+ mascotas',
                'tipo' => 'Porcentaje',
                'valor' => 14.00,
                'fecha_inicio' => Carbon::now()->subDays(80),
                'fecha_fin' => Carbon::now()->addMonths(9),
                'usos_maximos' => null,
                'usos_por_cliente' => 6,
                'monto_minimo' => 45.00,
                'activa' => true,
            ],
            [
                'nombre' => 'Cirugía Menor Descuento',
                'descripcion' => '$50 de descuento en cirugías menores',
                'tipo' => 'Monto_Fijo',
                'valor' => 50.00,
                'fecha_inicio' => Carbon::now()->subDays(12),
                'fecha_fin' => Carbon::now()->addMonths(2),
                'usos_maximos' => 60,
                'usos_por_cliente' => 1,
                'monto_minimo' => 300.00,
                'activa' => true,
            ]
        ];

        foreach ($promociones as $promocion) {
            DB::table('promociones')->insert([
                'nombre' => $promocion['nombre'],
                'descripcion' => $promocion['descripcion'],
                'tipo' => $promocion['tipo'],
                'valor' => $promocion['valor'],
                'fecha_inicio' => $promocion['fecha_inicio'],
                'fecha_fin' => $promocion['fecha_fin'],
                'usos_maximos' => $promocion['usos_maximos'],
                'usos_por_cliente' => $promocion['usos_por_cliente'],
                'monto_minimo' => $promocion['monto_minimo'],
                'activa' => $promocion['activa'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
