<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProveedoresSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('proveedores')->insert([
            ['nombre' => 'VetSupply Ecuador S.A.', 'ruc' => '1791234567001', 'telefono' => '022345678', 'email' => 'ventas@vetsupply.ec', 'direccion' => 'Av. América N39-123 y Whymper, Quito', 'contacto_principal' => 'Juan Pérez', 'productos_suministrados' => 'Medicamentos veterinarios, vacunas, antiparasitarios', 'tipo' => 'Farmaceutico', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Pet Food Distributors', 'ruc' => '1791234568001', 'telefono' => '023456789', 'email' => 'pedidos@petfood.ec', 'direccion' => 'Parque Industrial, Vía Daule Km 8, Guayaquil', 'contacto_principal' => 'María González', 'productos_suministrados' => 'Alimentos balanceados, snacks, suplementos', 'tipo' => 'Alimentos', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Equipos Médicos Vet S.A.', 'ruc' => '1791234569001', 'telefono' => '024567890', 'email' => 'info@equiposvet.ec', 'direccion' => 'Calle Coruña E25-67 y 6 de Diciembre, Quito', 'contacto_principal' => 'Carlos Rodríguez', 'productos_suministrados' => 'Equipos de diagnóstico, instrumental quirúrgico', 'tipo' => 'Equipos', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Accesorios Pet World', 'ruc' => '1791234570001', 'telefono' => '025678901', 'email' => 'compras@petworld.ec', 'direccion' => 'Mall del Sol, Local 234, Guayaquil', 'contacto_principal' => 'Ana Martínez', 'productos_suministrados' => 'Collares, correas, juguetes, camas', 'tipo' => 'Accesorios', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Laboratorios VetChem', 'ruc' => '1791234571001', 'telefono' => '026789012', 'email' => 'laboratorio@vetchem.ec', 'direccion' => 'Zona Industrial Los Ángeles, Cuenca', 'contacto_principal' => 'Dr. Luis Herrera', 'productos_suministrados' => 'Medicamentos especializados, análisis clínicos', 'tipo' => 'Farmaceutico', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Royal Canin Ecuador', 'ruc' => '1791234572001', 'telefono' => '027890123', 'email' => 'distribucion@royalcanin.ec', 'direccion' => 'Av. Eloy Alfaro N35-09 y Portugal, Quito', 'contacto_principal' => 'Patricia Ramírez', 'productos_suministrados' => 'Alimentos premium para perros y gatos', 'tipo' => 'Alimentos', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Hill\'s Pet Nutrition', 'ruc' => '1791234573001', 'telefono' => '028901234', 'email' => 'ventas@hills.ec', 'direccion' => 'Centro Empresarial Las Cámaras, Torre A, Piso 8, Quito', 'contacto_principal' => 'Miguel Torres', 'productos_suministrados' => 'Alimentos terapéuticos, dietas especiales', 'tipo' => 'Alimentos', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Zoetis Ecuador', 'ruc' => '1791234574001', 'telefono' => '029012345', 'email' => 'contacto@zoetis.ec', 'direccion' => 'Edif. World Trade Center, Torre B, Piso 12, Guayaquil', 'contacto_principal' => 'Dra. Carmen Silva', 'productos_suministrados' => 'Vacunas, medicamentos especializados', 'tipo' => 'Farmaceutico', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Pro Plan Ecuador', 'ruc' => '1791234575001', 'telefono' => '020123456', 'email' => 'pedidos@proplan.ec', 'direccion' => 'Vía Samborondón Km 2.5, Guayaquil', 'contacto_principal' => 'Roberto Castro', 'productos_suministrados' => 'Alimentos balanceados premium', 'tipo' => 'Alimentos', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Virbac Ecuador', 'ruc' => '1791234576001', 'telefono' => '021234567', 'email' => 'info@virbac.ec', 'direccion' => 'Av. República E7-226 y Almagro, Quito', 'contacto_principal' => 'Elena Morales', 'productos_suministrados' => 'Medicamentos dermatológicos, vacunas', 'tipo' => 'Farmaceutico', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Kong Company Ecuador', 'ruc' => '1791234577001', 'telefono' => '022345679', 'email' => 'distribuidores@kong.ec', 'direccion' => 'Calle Alemania N30-185 y Mariana de Jesús, Quito', 'contacto_principal' => 'Fernando Vargas', 'productos_suministrados' => 'Juguetes educativos, accesorios de entretenimiento', 'tipo' => 'Accesorios', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Bayer Animal Health', 'ruc' => '1791234578001', 'telefono' => '023456780', 'email' => 'animalhealth@bayer.ec', 'direccion' => 'Edif. Riverside, Piso 15, Av. Francisco de Orellana, Guayaquil', 'contacto_principal' => 'Dra. Sofía Jiménez', 'productos_suministrados' => 'Antiparasitarios, medicamentos sistémicos', 'tipo' => 'Farmaceutico', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Flexi Ecuador', 'ruc' => '1791234579001', 'telefono' => '024567891', 'email' => 'ventas@flexi.ec', 'direccion' => 'Av. Naciones Unidas E2-17 y Av. América, Quito', 'contacto_principal' => 'David Mendoza', 'productos_suministrados' => 'Correas extensibles, collares de diseño', 'tipo' => 'Accesorios', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Nutrique Ecuador', 'ruc' => '1791234580001', 'telefono' => '025678902', 'email' => 'distribucion@nutrique.ec', 'direccion' => 'Km 14.5 Vía a Daule, Guayaquil', 'contacto_principal' => 'Andrea Nuñez', 'productos_suministrados' => 'Alimentos superpremium, dietas especializadas', 'tipo' => 'Alimentos', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'MSD Animal Health', 'ruc' => '1791234581001', 'telefono' => '026789013', 'email' => 'msdah@msd.ec', 'direccion' => 'Edif. Centrum, Piso 9, Av. Francisco de Orellana, Guayaquil', 'contacto_principal' => 'Dr. Javier Espinoza', 'productos_suministrados' => 'Vacunas, medicamentos preventivos', 'tipo' => 'Farmaceutico', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Ferplast Ecuador', 'ruc' => '1791234582001', 'telefono' => '027890124', 'email' => 'pedidos@ferplast.ec', 'direccion' => 'Av. 6 de Diciembre N26-123 y Lincoln, Quito', 'contacto_principal' => 'Natalia Romero', 'productos_suministrados' => 'Transportadoras, casas para mascotas', 'tipo' => 'Accesorios', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Farmacia Veterinaria Central', 'ruc' => '1791234583001', 'telefono' => '028901235', 'email' => 'farmacia@vetcentral.ec', 'direccion' => 'Av. 10 de Agosto N18-49 y Carrión, Quito', 'contacto_principal' => 'Isabel Delgado', 'productos_suministrados' => 'Medicamentos genéricos, material quirúrgico', 'tipo' => 'Farmaceutico', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Eukanuba Ecuador', 'ruc' => '1791234584001', 'telefono' => '029012346', 'email' => 'distribuidor@eukanuba.ec', 'direccion' => 'Centro Comercial El Bosque, Local 145, Quito', 'contacto_principal' => 'Gabriela Peña', 'productos_suministrados' => 'Alimentos premium para razas específicas', 'tipo' => 'Alimentos', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Tecnología Veterinaria S.A.', 'ruc' => '1791234585001', 'telefono' => '020123457', 'email' => 'tecnologia@tecnovet.ec', 'direccion' => 'Parque Tecnológico, Mz. A, Lote 15, Quito', 'contacto_principal' => 'Dr. Ricardo Paredes', 'productos_suministrados' => 'Equipos de rayos X, ecógrafos, monitores', 'tipo' => 'Equipos', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'Natural Pet Food', 'ruc' => '1791234586001', 'telefono' => '021234568', 'email' => 'natural@petfood.ec', 'direccion' => 'Av. Orellana 1234 y Amazonas, Quito', 'contacto_principal' => 'Cristina Aguilar', 'productos_suministrados' => 'Alimentos orgánicos, snacks naturales', 'tipo' => 'Alimentos', 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
