<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VentasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ventas = [
            [
                'numero_factura' => 'FAC-2025-0001',
                'cliente_id' => 1,
                'empleado_id' => 11, // Sofía Cajero
                'fecha_venta' => Carbon::now()->subDays(5)->setTime(10, 30),
                'subtotal' => 155.40,
                'impuesto' => 18.65,
                'descuento' => 15.54,
                'total' => 158.51,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 41.49,
                'observaciones' => 'Pago con efectivo $200',
            ],
            [
                'numero_factura' => 'FAC-2025-0002',
                'cliente_id' => 2,
                'empleado_id' => 12, // Roberto Cajero
                'fecha_venta' => Carbon::now()->subDays(4)->setTime(14, 15),
                'subtotal' => 234.70,
                'impuesto' => 28.16,
                'descuento' => 0.00,
                'total' => 262.86,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 0.00,
                'observaciones' => 'Pago con tarjeta de crédito',
            ],
            [
                'numero_factura' => 'FAC-2025-0003',
                'cliente_id' => 3,
                'empleado_id' => 1, // Valeria Cajero
                'fecha_venta' => Carbon::now()->subDays(3)->setTime(9, 45),
                'subtotal' => 89.50,
                'impuesto' => 10.74,
                'descuento' => 8.95,
                'total' => 91.29,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 8.71,
                'observaciones' => 'Descuento cliente nuevo aplicado',
            ],
            [
                'numero_factura' => 'FAC-2025-0004',
                'cliente_id' => null, // Venta sin cliente registrado
                'empleado_id' => 11,
                'fecha_venta' => Carbon::now()->subDays(2)->setTime(16, 20),
                'subtotal' => 45.80,
                'impuesto' => 5.50,
                'descuento' => 0.00,
                'total' => 51.30,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 8.70,
                'observaciones' => 'Cliente ocasional - pago efectivo $60',
            ],
            [
                'numero_factura' => 'FAC-2025-0005',
                'cliente_id' => 5,
                'empleado_id' => 12,
                'fecha_venta' => Carbon::now()->subDays(1)->setTime(11, 10),
                'subtotal' => 312.45,
                'impuesto' => 37.49,
                'descuento' => 31.25,
                'total' => 318.69,
                'estado' => 'Pagada',
                'tipo_venta' => 'Credito',
                'cambio' => 0.00,
                'observaciones' => 'Crédito aprobado 30 días',
            ],
            [
                'numero_factura' => 'FAC-2025-0006',
                'cliente_id' => 6,
                'empleado_id' => 2,
                'fecha_venta' => Carbon::now()->subHours(5),
                'subtotal' => 127.90,
                'impuesto' => 15.35,
                'descuento' => 12.79,
                'total' => 130.46,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 19.54,
                'observaciones' => 'Cliente frecuente - descuento fidelidad',
            ],
            [
                'numero_factura' => 'FAC-2025-0007',
                'cliente_id' => 7,
                'empleado_id' => 11,
                'fecha_venta' => Carbon::now()->subDays(6)->setTime(13, 30),
                'subtotal' => 198.60,
                'impuesto' => 23.83,
                'descuento' => 0.00,
                'total' => 222.43,
                'estado' => 'Pagada',
                'tipo_venta' => 'Mixto',
                'cambio' => 0.00,
                'observaciones' => 'Pago: $100 efectivo + $122.43 tarjeta',
            ],
            [
                'numero_factura' => 'FAC-2025-0008',
                'cliente_id' => 8,
                'empleado_id' => 12,
                'fecha_venta' => Carbon::now()->subDays(7)->setTime(15, 45),
                'subtotal' => 456.80,
                'impuesto' => 54.82,
                'descuento' => 45.68,
                'total' => 465.94,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 34.06,
                'observaciones' => 'Compra por volumen - descuento aplicado',
            ],
            [
                'numero_factura' => 'FAC-2025-0009',
                'cliente_id' => 9,
                'empleado_id' => 3,
                'fecha_venta' => Carbon::now()->subDays(8)->setTime(12, 15),
                'subtotal' => 78.30,
                'impuesto' => 9.40,
                'descuento' => 7.83,
                'total' => 79.87,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 0.13,
                'observaciones' => 'Descuento senior aplicado',
            ],
            [
                'numero_factura' => 'FAC-2025-0010',
                'cliente_id' => 10,
                'empleado_id' => 11,
                'fecha_venta' => Carbon::now()->subDays(9)->setTime(10, 0),
                'subtotal' => 345.20,
                'impuesto' => 41.42,
                'descuento' => 0.00,
                'total' => 386.62,
                'estado' => 'Pendiente',
                'tipo_venta' => 'Credito',
                'cambio' => 0.00,
                'observaciones' => 'Pendiente de aprobación crediticia',
            ],
            [
                'numero_factura' => 'FAC-2025-0011',
                'cliente_id' => 11,
                'empleado_id' => 12,
                'fecha_venta' => Carbon::now()->subDays(10)->setTime(16, 30),
                'subtotal' => 167.45,
                'impuesto' => 20.09,
                'descuento' => 16.75,
                'total' => 170.79,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 29.21,
                'observaciones' => 'Promoción navideña aplicada',
            ],
            [
                'numero_factura' => 'FAC-2025-0012',
                'cliente_id' => null,
                'empleado_id' => 4,
                'fecha_venta' => Carbon::now()->subDays(11)->setTime(8, 45),
                'subtotal' => 92.15,
                'impuesto' => 11.06,
                'descuento' => 0.00,
                'total' => 103.21,
                'estado' => 'Cancelada',
                'tipo_venta' => 'Contado',
                'cambio' => 0.00,
                'observaciones' => 'Venta cancelada por error en productos',
            ],
            [
                'numero_factura' => 'FAC-2025-0013',
                'cliente_id' => 13,
                'empleado_id' => 11,
                'fecha_venta' => Carbon::now()->subDays(12)->setTime(14, 20),
                'subtotal' => 289.70,
                'impuesto' => 34.76,
                'descuento' => 28.97,
                'total' => 295.49,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 4.51,
                'observaciones' => 'Descuento por referido aplicado',
            ],
            [
                'numero_factura' => 'FAC-2025-0014',
                'cliente_id' => 14,
                'empleado_id' => 12,
                'fecha_venta' => Carbon::now()->subDays(13)->setTime(11, 35),
                'subtotal' => 156.80,
                'impuesto' => 18.82,
                'descuento' => 0.00,
                'total' => 175.62,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 24.38,
                'observaciones' => 'Pago con efectivo $200',
            ],
            [
                'numero_factura' => 'FAC-2025-0015',
                'cliente_id' => 15,
                'empleado_id' => 5,
                'fecha_venta' => Carbon::now()->subDays(14)->setTime(9, 15),
                'subtotal' => 67.25,
                'impuesto' => 8.07,
                'descuento' => 6.73,
                'total' => 68.59,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 1.41,
                'observaciones' => 'Primera compra - descuento bienvenida',
            ],
            [
                'numero_factura' => 'FAC-2025-0016',
                'cliente_id' => 16,
                'empleado_id' => 11,
                'fecha_venta' => Carbon::now()->subDays(15)->setTime(15, 50),
                'subtotal' => 423.90,
                'impuesto' => 50.87,
                'descuento' => 42.39,
                'total' => 432.38,
                'estado' => 'Pagada',
                'tipo_venta' => 'Credito',
                'cambio' => 0.00,
                'observaciones' => 'Crédito 45 días - compra mayor',
            ],
            [
                'numero_factura' => 'FAC-2025-0017',
                'cliente_id' => 17,
                'empleado_id' => 12,
                'fecha_venta' => Carbon::now()->subDays(16)->setTime(13, 10),
                'subtotal' => 134.50,
                'impuesto' => 16.14,
                'descuento' => 13.45,
                'total' => 137.19,
                'estado' => 'Devuelta',
                'tipo_venta' => 'Contado',
                'cambio' => 0.00,
                'observaciones' => 'Devolución por producto defectuoso',
            ],
            [
                'numero_factura' => 'FAC-2025-0018',
                'cliente_id' => 18,
                'empleado_id' => 6,
                'fecha_venta' => Carbon::now()->subDays(17)->setTime(10, 25),
                'subtotal' => 278.45,
                'impuesto' => 33.41,
                'descuento' => 0.00,
                'total' => 311.86,
                'estado' => 'Pagada',
                'tipo_venta' => 'Mixto',
                'cambio' => 0.00,
                'observaciones' => '$150 efectivo + $161.86 tarjeta débito',
            ],
            [
                'numero_factura' => 'FAC-2025-0019',
                'cliente_id' => 19,
                'empleado_id' => 11,
                'fecha_venta' => Carbon::now()->subDays(18)->setTime(16, 40),
                'subtotal' => 89.90,
                'impuesto' => 10.79,
                'descuento' => 8.99,
                'total' => 91.70,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 8.30,
                'observaciones' => 'Descuento estudiante aplicado',
            ],
            [
                'numero_factura' => 'FAC-2025-0020',
                'cliente_id' => 20,
                'empleado_id' => 12,
                'fecha_venta' => Carbon::now()->subDays(19)->setTime(12, 55),
                'subtotal' => 567.80,
                'impuesto' => 68.14,
                'descuento' => 56.78,
                'total' => 579.16,
                'estado' => 'Pagada',
                'tipo_venta' => 'Contado',
                'cambio' => 20.84,
                'observaciones' => 'Compra mayor - descuento volumen',
            ]
        ];

        foreach ($ventas as $venta) {
            DB::table('ventas')->insert([
                'numero_factura' => $venta['numero_factura'],
                'cliente_id' => $venta['cliente_id'],
                'empleado_id' => $venta['empleado_id'],
                'fecha_venta' => $venta['fecha_venta'],
                'subtotal' => $venta['subtotal'],
                'impuesto' => $venta['impuesto'],
                'descuento' => $venta['descuento'],
                'total' => $venta['total'],
                'estado' => $venta['estado'],
                'tipo_venta' => $venta['tipo_venta'],
                'cambio' => $venta['cambio'],
                'observaciones' => $venta['observaciones'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
